import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-construction-subcontractor-backcharge-recovery",
  "engine": "recovery",
  "title": "Construction Subcontractor Backcharge Recovery",
  "shortTitle": "Construction Subcontractor Backcharge Recovery",
  "tagline": "Document and recover costs caused by subcontractor scope failures, rework, cleanup, and schedule impacts.",
  "industry": "Construction Cost Recovery",
  "buyer": "General contractors and construction managers",
  "uiPort": 4721,
  "apiPort": 5721,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Construction Subcontractor Backcharge Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions in one accountable workflow. Document and recover costs caused by subcontractor scope failures, rework, cleanup, and schedule impacts.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Construction Subcontractor Backcharge Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("subcontract-scope-library","CSB01","Subcontract scope library","Execute subcontract scope library using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed subcontract scope library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Subcontract scope library Reference","text","CSB01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("daily-log-ingestion","CSB02","Daily log ingestion","Execute daily log ingestion using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed daily log ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Daily log ingestion Reference","text","CSB02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("issue-notice-tracking","CSB03","Issue notice tracking","Execute issue notice tracking using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed issue notice tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Issue notice tracking Reference","text","CSB03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("responsible-party-analysis","CSB04","Responsible party analysis","Execute responsible party analysis using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed responsible party analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Responsible party analysis Reference","text","CSB04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("labor-cost-reconstruction","CSB05","Labor cost reconstruction","Execute labor cost reconstruction using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed labor cost reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Labor cost reconstruction Reference","text","CSB05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("equipment-cost-reconstruction","CSB06","Equipment cost reconstruction","Execute equipment cost reconstruction using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed equipment cost reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Equipment cost reconstruction Reference","text","CSB06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("material-cost-reconstruction","CSB07","Material cost reconstruction","Execute material cost reconstruction using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed material cost reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Material cost reconstruction Reference","text","CSB07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("rework-quantity-validation","CSB08","Rework quantity validation","Execute rework quantity validation using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed rework quantity validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Rework quantity validation Reference","text","CSB08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("cleanup-allocation","CSB09","Cleanup allocation","Execute cleanup allocation using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed cleanup allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Cleanup allocation Reference","text","CSB09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("schedule-impact-calculation","CSB10","Schedule impact calculation","Execute schedule impact calculation using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed schedule impact calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Schedule impact calculation Reference","text","CSB10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("contract-notice-compliance","CSB11","Contract notice compliance","Execute contract notice compliance using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed contract notice compliance decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Contract notice compliance Reference","text","CSB11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("backcharge-package-generation","CSB12","Backcharge package generation","Execute backcharge package generation using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed backcharge package generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Backcharge package generation Reference","text","CSB12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("subcontractor-response-workflow","CSB13","Subcontractor response workflow","Execute subcontractor response workflow using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed subcontractor response workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Subcontractor response workflow Reference","text","CSB13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("deduction-reconciliation","CSB14","Deduction reconciliation","Execute deduction reconciliation using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed deduction reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Deduction reconciliation Reference","text","CSB14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]}),
feature("project-trade-analytics","CSB15","Project trade analytics","Execute project trade analytics using subcontracts, scopes, daily logs, notices, labor, equipment, materials, rework, cleanup, schedule impacts, invoices, and deductions.","Produce a governed project trade analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subcontractor","text","Project / Subcontractor · Standard Case"],["caseReference","Project trade analytics Reference","text","CSB15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1580000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1911800],["domainDriver","Backcharge Cause","select","Rework",["Rework","Cleanup","Schedule delay"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Subcontract scope library case","Daily log ingestion case","Issue notice tracking case","Responsible party analysis case","Labor cost reconstruction case"]})
]);
